export const CANVAS_CONFIG = {
  ARENA_WIDTH: 2600,
  ARENA_HEIGHT: 2000,
  DEFAULT_VIEWPORT_WIDTH: 1200,
  DEFAULT_VIEWPORT_HEIGHT: 800,
};

export const PLAYER_CONFIG = {
  RADIUS: 20,
  SPEED: 230,
  DASH_SPEED: 520,
  DASH_DURATION: 0.22,
  DASH_COOLDOWN: 1.2,
  MAX_HP: 120,
  HP_REGEN: 1.2, // hp per second
  ATTACK_COOLDOWN: 0.32, // seconds between regular attacks
  ATTACK_DAMAGE: 32,
  CRIT_CHANCE: 0.18, // 18% base crit
  CRIT_MULTIPLIER: 2.0,
  PROJECTILE_SPEED: 580,
  PROJECTILE_LIFETIME: 1.1,
  SPECIAL_COOLDOWN: 4.5, // whirlwind AoE
  SPECIAL_DAMAGE: 65,
  SPECIAL_RADIUS: 140,
  INVULNERABLE_TIME: 0.45, // seconds after getting hit
  MAGNET_RADIUS: 130, // pickup range
};

export const ENEMY_TYPES = {
  goblin: {
    id: 'goblin',
    name: 'Goblin Scamp',
    radius: 16,
    baseHp: 42,
    baseDamage: 9,
    baseSpeed: 145,
    attackCooldown: 0.8,
    attackRange: 26,
    behavior: 'flank',
    xpReward: 16,
    goldChance: 0.65,
    goldMin: 2,
    goldMax: 6,
    color: '#34d399',
    accentColor: '#059669',
    unlockWave: 1,
    weight: 1.0,
  },
  zombie: {
    id: 'zombie',
    name: 'Undead Shambler',
    radius: 21,
    baseHp: 110,
    baseDamage: 16,
    baseSpeed: 68,
    attackCooldown: 1.1,
    attackRange: 32,
    behavior: 'relentless',
    xpReward: 26,
    goldChance: 0.75,
    goldMin: 4,
    goldMax: 10,
    color: '#06b6d4',
    accentColor: '#0e7490',
    unlockWave: 1,
    weight: 0.8,
  },
  orc: {
    id: 'orc',
    name: 'Orc Berserker',
    radius: 27,
    baseHp: 240,
    baseDamage: 28,
    baseSpeed: 88,
    chargeSpeed: 270,
    attackCooldown: 1.4,
    attackRange: 38,
    behavior: 'brute_charge',
    xpReward: 55,
    goldChance: 0.85,
    goldMin: 10,
    goldMax: 22,
    knockbackResistance: 0.65,
    color: '#f97316',
    accentColor: '#c2410c',
    unlockWave: 2,
    weight: 0.5,
  },
  archer: {
    id: 'archer',
    name: 'Skeleton Archer',
    radius: 17,
    baseHp: 65,
    baseDamage: 14,
    baseSpeed: 112,
    attackCooldown: 2.2,
    attackRange: 310,
    projectileSpeed: 380,
    projectileRadius: 5,
    behavior: 'ranged_kiter',
    xpReward: 42,
    goldChance: 0.8,
    goldMin: 8,
    goldMax: 16,
    color: '#a8a29e',
    accentColor: '#e2e8f0',
    unlockWave: 3,
    weight: 0.45,
  },
  demon: {
    id: 'demon',
    name: 'Abyssal Demon',
    radius: 23,
    baseHp: 175,
    baseDamage: 24,
    baseSpeed: 102,
    attackCooldown: 2.6,
    attackRange: 280,
    projectileSpeed: 320,
    projectileRadius: 8,
    behavior: 'caster_teleport',
    xpReward: 80,
    goldChance: 0.9,
    goldMin: 18,
    goldMax: 35,
    knockbackResistance: 0.4,
    color: '#ef4444',
    accentColor: '#881337',
    unlockWave: 4,
    weight: 0.35,
  },
};

export const BOSS_CONFIG = {
  id: 'boss_overlord',
  name: 'Malakor, Infernal Overlord',
  radius: 46,
  baseHp: 1400,
  baseDamage: 36,
  baseSpeed: 75,
  enragedSpeed: 110,
  attackCooldown: 1.5,
  xpReward: 600,
  goldMin: 120,
  goldMax: 250,
  color: '#dc2626',
  accentColor: '#7f1d1d',
  unlockWave: 5,
};

export const DIFFICULTY_SCALING = {
  hpScalePerWave: 0.22,
  damageScalePerWave: 0.16,
  speedScalePerWave: 0.035,
  maxSpeedBonus: 0.35,
  spawnIntervalInitial: 1.6, // seconds between spawns
  spawnIntervalMin: 0.45,
  waveDuration: 45, // seconds per regular wave
  maxEnemiesBase: 18,
  maxEnemiesPerWave: 4,
  maxEnemiesHardCap: 60,
};
